---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(survival)
library(visR)
library(dplyr)
library(ggplot2)

DATASET <- paste0("NCCTG Lung Cancer Dataset (from survival package ", 
                  packageVersion("survival"), ")")

# Globql formatting options
options(digits = 3)

# Global ggplot settings
theme_set(theme_classic())

# Global table settings 
options(DT.options = list(pageLength = 10, 
                          language = list(search = 'Filter:'), 
                          scrollX = TRUE))
```

## R Markdown


```{r cohort}
data(lung)
lung_cohort <- lung %>% 
    dplyr::rename(ECOG = ph.ecog,
                  Karnofsky = ph.karno,
                  SITEID = inst,
                  CNSR = status,
                  AVAL = time,
                  WEIGHT = wt.loss
                 ) %>% 
    dplyr::mutate(USUBJID = sprintf("Pat%03d", row_number()),
                  SEX = factor(if_else(sex == 1, "male", "female")),
                  CNSR = if_else(CNSR == 2, 1, 0),
                  SUBGR1 = factor(case_when(ECOG == 0 ~ "0 asymptomatic",
                                            ECOG == 1 ~ "1 ambulatory",
                                            ECOG == 2 ~ "2 in bed less than 50% of day",
                                            ECOG == 3 ~ "3 in bed more than 50% of day",
                                            ECOG == 4 ~ "4 bedbound",
                                            ECOG == 5 ~ "5 dead")
                                 ),
                  AGEGR1 = factor(case_when(age < 30 ~ "< 30y",
                                            age >= 30 & age <= 50 ~ "30-50y",
                                            age > 50 & age <= 70 ~ "51-70y",
                                            age > 70 ~ "> 70y"),
                                  levels=c("< 30y", "30-50y", "51-70y", "> 70y")
                                 )
                 ) %>%
    dplyr::select(USUBJID, SITEID, SEX, AGEGR1, WEIGHT, SUBGR1, AVAL, CNSR)
  
```
```{r}
lung_cohort <- lung_cohort %>%
  dplyr::filter(!is.na(SUBGR1),
                !is.na(WEIGHT),
                !is.na(CNSR),
                 AVAL >= 0
                )
```

## KM
```{r}
lung_cohort %>%
  estimate_KM(strata = "SEX", conf.int = 0.90)
```
```{r}
lung_cohort %>%
  estimate_KM(strata = "SEX", conf.int = 0.90) %>%
  visR::plot(legend_position = "right", x_unit = "Days") %>%
  add_CI(alpha = 0.2, style = "ribbon") %>%
  add_CNSR(shape = 3, size = 2) %>%
  add_risktable(min_at_risk = 0,
                statlist= c("n.risk", "n.event", "n.censor"),
                label = c("At risk", "Event", "Censor"),
                collapse = F
               )
```

