---
title: "plot_survival"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{plot_survival}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

---
title: "time_to_event"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{time_to_event}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(visR)
```

```{r}
library(survival)
library(magrittr)
library(dplyr)
library(ggplot2)
library(broom)
library(patchwork)

fit <- survfit(Surv(time, status) ~ sex, data = lung) 
a <- fit %>% 
  tidy() %>% 
  visr_plot_surv()
a
```


Change and update the plot asthestics. 

```{r}
a <- 
  a + 
  ggtitle("Change the title") +
  xlab("Days from index measurement") +
  ylab("Survival") +
  theme_classic() 

a
```

Add annotations. 

```{r}
library(ggrepel)
a <- a +
  geom_text_repel(data = fit %>% 
                    tidy() %>% 
                    group_by(strata) %>% 
                    slice(n()),
    aes(label = strata),
    size = 4.5,
    point.padding = .2,
    box.padding = .3,
    force = 1,
    min.segment.length = 0
  )

a
```


Display risk table

```{r}
b <- visr_plot_risk(fit, 500) 
b
```


```{r}
a / b
```

TODO: How to add to displayed ggplot object. ggproto? e.g. add facetting by strata. 