---
title: "Summary Tables"
author: Charlotta Fruechtenicht
output:
    bookdown::html_document2:
        code_folding: hide
        toc: true
        toc_float:
            collapsed: false
---
```{r}
library(dplyr)
library(survival)
library(visR)
```

Summary tables can be easily created and rendered using visR.

```{r}
data(ovarian)

ovarian_pts <- ovarian %>% 
  select(-fustat) %>% 
  mutate(age_group = factor(case_when(age <= 50 ~ "<= 50 years",
                               age <= 60 ~ "<= 60 years",
                               age <= 70 ~ "<= 70 years",
                               TRUE ~ "> 70 years")),
         rx = factor(rx),
         ecog.ps = factor(ecog.ps)) %>% 
  select(age, age_group, everything())
```

# Table with overall summary statistics
```{r}
# create table 1
tab1_overall <- vr_create_tableone(ovarian_pts) 

# render table
tab1_overall %>% vr_render_table("Overview over ovarian dataset")
```

# Table with summary statistics stratified by age groups
```{r}
# create table
tab1_groups <- vr_create_tableone(ovarian_pts, strata = c("age_group"))

# render table
tab1_groups %>% vr_render_table(caption = "Ovarian patients")
```

## Render table using kable
```{r}
tab1_groups %>% vr_render_table(engine = "kable", caption = "Ovarian patients")
```



